# Phoebus-OS AP — RTL8832BR (5 GHz only: band_cap:5G)
interface=wlan1
driver=nl80211
bridge=br0
ctrl_interface=/var/run/hostapd

ssid=Phoebus-OS-2G
country_code=US
hw_mode=g
channel=6
ieee80211d=1

wmm_enabled=1
ieee80211n=1
ht_capab=[SHORT-GI-20][SHORT-GI-40]

auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=phoebus12345
